### PR TITLE
loader

### PR DESCRIPTION
**Pull request by bilalbutt044**
loader for ecommerce Website home page. (products and categories)

### CODE REVIEW

**Comment by danilowoz** [comment]
Thanks and welcome to hacktoberfest 🍻

**Comment by bilalbutt044** [comment]
Thanks .

**Comment by bilalbutt044** [comment]
Will my PR count for hacktoberfest?

**Comment by danilowoz** [comment]
Probably it will

**Comment by danilowoz** [comment]
@all-contributors please add @bilalbutt044 for content

**Pull request merged**
